name: terapizone
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter_localizations:
    sdk: flutter
  agora_rtc_engine: ^5.2.0
  snapping_sheet: ^3.1.0
  carousel_slider: ^4.0.0
  cupertino_icons: ^1.0.2
  firebase: ^9.0.2
  firebase_auth: ^3.2.0
  dio: ^4.0.4
  firebase_core: ^1.10.0
  firebase_messaging: ^11.1.0
  fl_chart: ^0.40.2
  flutter:
    sdk: flutter
  flutter_html: ^2.1.4
  flutter_local_notifications: ^9.1.2
  flutter_svg: ^0.23.0+1
  get: ^4.1.4
  get_storage: ^2.0.2
  hive: ^2.0.4
  http: ^0.13.3
  image_picker: ^0.8.3+3
  flutter_secure_storage: ^5.0.2
  intl: ^0.17.0
  jiffy: ^4.1.0
  just_audio: ^0.9.7
  loading_indicator: ^3.0.2
  path_provider: ^2.0.3
  permission_handler: ^8.1.6
  record: ^3.0.0
  table_calendar: ^3.0.1
  url_launcher: ^6.0.12
  vimeo_player_flutter: ^0.0.3+1
  wakelock: ^0.5.6
  webviewx: ^0.2.1
  signalr_core: ^1.1.1
  signalr_flutter: ^0.1.1
  retry: ^3.1.0

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/
    - assets/icons/
    - assets/images/
    - assets/fonts/
    - assets/svg/

  fonts:
    - family: SF-Pro-Display-Regular
      fonts:
        - asset: assets/fonts/SF-Pro-Display-Regular.otf
    - family: Montserrat-Medium
      fonts:
        - asset: assets/fonts/Montserrat-Medium.ttf
    - family: Montserrat-Bold
      fonts:
        - asset: assets/fonts/Montserrat-Bold.ttf
    - family: Montserrat-SemiBold
      fonts:
        - asset: assets/fonts/Montserrat-SemiBold.ttf
